# Generated by Django 4.2.4 on 2023-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
