# Generated by Django 4.2.4 on 2023-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_category_options_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_it",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ua",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ua",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="name_en",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="section",
            name="name_it",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="section",
            name="name_ua",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
