# Generated by Django 4.2.4 on 2023-08-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0003_category_name_en_category_name_it_category_name_ua_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name_ua",
            new_name="name_uk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description_ua",
            new_name="description_uk",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="name_ua",
            new_name="name_uk",
        ),
    ]
